# Generated by Django 5.2.7 on 2025-12-07 06:17

import file_handler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('substation', 'Substation'), ('company_profile', 'Company Profile'), ('general', 'General')], default='substation', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=file_handler.models.user_directory_path),
        ),
    ]
