# Generated by Django 5.2.7 on 2025-12-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0002_uploadedfile_category_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(blank=True, choices=[('substation', 'Substation'), ('company_profile', 'Company Profile'), ('general', 'General')], default='substation', help_text='Select the category of the file.', max_length=50, null=True),
        ),
    ]
