# Generated by Django 5.2.7 on 2025-10-06 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('client_name', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='pages.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=400)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(default='Nos', max_length=60)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.quotationpart')),
            ],
        ),
    ]
