# Generated by Django 5.2.7 on 2025-10-06 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_quotationtemplate_remove_quotationitem_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.AddField(
            model_name='quotationtemplateitem',
            name='group_name',
            field=models.CharField(default='Main Part', max_length=100),
        ),
        migrations.CreateModel(
            name='QuotationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pages.quotation')),
            ],
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.quotationgroup'),
            preserve_default=False,
        ),
    ]
