# Generated by Django 5.2.7 on 2025-10-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_quotationitem_quotation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='quotationtemplateitem',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='qty',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationtemplateitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quotationtemplateitem',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotationtemplateitem',
            name='qty',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='quotationtemplateitem',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
