# Generated by Django 5.2.7 on 2025-10-07 05:52

import django.db.models.deletion
from django.db import migrations, models

def migrate_data(apps, schema_editor):
    QuotationItem = apps.get_model('pages', 'QuotationItem')
    QuotationTemplateItem = apps.get_model('pages', 'QuotationTemplateItem')
    Item = apps.get_model('pages', 'Item')
    ItemGroup = apps.get_model('pages', 'ItemGroup')
    Unit = apps.get_model('pages', 'Unit')

    for old_item in QuotationItem.objects.all():
        group, _ = ItemGroup.objects.get_or_create(name=old_item.group.name)
        unit, _ = Unit.objects.get_or_create(name=old_item.unit)
        new_item, _ = Item.objects.get_or_create(
            name=old_item.description,
            group=group,
            unit=unit,
            unit_price=old_item.unit_price
        )
        old_item.item = new_item
        old_item.save()

    for old_item in QuotationTemplateItem.objects.all():
        group, _ = ItemGroup.objects.get_or_create(name=old_item.group_name)
        unit, _ = Unit.objects.get_or_create(name=old_item.unit)
        new_item, _ = Item.objects.get_or_create(
            name=old_item.description,
            group=group,
            unit=unit,
            unit_price=old_item.unit_price
        )
        old_item.item = new_item
        old_item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_demo_data_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.item'),
        ),
        migrations.AddField(
            model_name='quotationtemplateitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.itemgroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.unit'),
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name='quotationitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='quotationtemplateitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quotationtemplateitem',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='quotationtemplateitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='quotationtemplateitem',
            name='unit_price',
        ),
    ]
