# Generated by Django 5.2.7 on 2025-10-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_non_nullable_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtemplateitem',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
