# Generated by Django 5.2.7 on 2025-10-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_quotationtemplateitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit_price',
        ),
    ]
