# Generated by Django 5.2.7 on 2025-10-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_item_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
