# Generated by Django 5.2.7 on 2025-11-01 11:14

from django.db import migrations
from django.db.models import Count

def remove_duplicate_items(apps, schema_editor):
    Item = apps.get_model('pages', 'Item')
    duplicates = (
        Item.objects.values('group', 'name')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for duplicate in duplicates:
        items = Item.objects.filter(
            group=duplicate['group'], name=duplicate['name']
        ).order_by('id')

        # Keep the first item and rename the rest
        for i, item in enumerate(items[1:]):
            item.name = f"{item.name} ({i + 1})"
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_item_unit_price'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_items),
    ]