# Generated by Django 5.2.7 on 2025-11-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20251101_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('group', 'name')},
        ),
    ]
