# Generated by Django 5.2.7 on 2025-11-04 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_quotationitem_qty_alter_item_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.unit'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.item'),
        ),
    ]
