# Generated by Django 5.2.7 on 2025-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_custom_item_in_quotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationtemplateitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='quotationtemplateitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
