# Generated by Django 5.2.7 on 2025-11-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_quotationtemplateitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('achieved', 'Achieved')], default='active', max_length=10),
        ),
    ]
