# Generated by Django 5.2.7 on 2025-11-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_quotation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
