# Generated by Django 5.2.7 on 2025-11-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_quotation_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='serial',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
