# Generated by Django 5.2.7 on 2025-11-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_quotation_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='serial',
        ),
    ]
