# Generated by Django 5.2.7 on 2025-11-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_quotation_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
