# Generated by Django 5.2.7 on 2025-12-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_quotation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
