# Generated by Django 5.2.7 on 2025-12-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('working', 'Working'), ('completed', 'Completed')], default='active', max_length=10),
        ),
    ]
